---
title: "Data manipulation"
output: html_document
date: "2023-11-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE) 
knitr::opts_chunk$set(warning = FALSE) 
options(kableExtra.auto_format = FALSE)
knitr::opts_chunk$set(fig.pos = "!H", out.extra = "")
knitr::knit_engines$set(text = function(options) {
  code <- paste(options$code, collapse = "\n")
})
knitr::opts_chunk$set(message=FALSE, tidy.opts=list(width.cutoff=75), tidy=TRUE) 
```

```{r}
library(tidycensus)
library(tidyverse)
library(readr)
library(survey)
library(srvyr)
library(convey)
library(dplyr)
library(tidyr)
library(plm)
library(ineq)
library(ggplot2)
library(scales)
library(car)
library(gtsummary)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(stargazer)
library(knitr)
library(kableExtra)
```

```{r}
setwd('E:/UBC/2023W1/ECON490/git repo')
raw <- read_sas('epcg19.sas7bdat')
```

```{r}
raw_select <- select(raw, REFYR, AGE, GENDER, MINRTY, ASIAN, BLACK,  WHITE, HISPANIC, RACETHM, 
               HCAPIN, MARIND, BSDGN, BTHST, BTHUS, COHORT,CTZN, CTZUSIN, 
               BAACYR, BAAYR3, BAPBPR, BAIND, BADGRUS,  D2DG, DGRDG, DGRYR, HDACY3,
               HDACYR, N2BAMED,  NBAMEBG, NBAMEMG, NBAMENG, 
               EARN, HRSWK, LFSTAT, SALARY, WKSWK, WKSYR, 
               EDDAD, EDMOM,
               EMSECSM, EMTP, EMUS,
               MGRNAT, MGROTH, MGRSOC,
               RESPLO3, RESPLOC, WTSURVY)
```

```{r}
data_recode <- raw_select %>%
  mutate(
    RACETHM = case_when(
      RACETHM =="1"	~ "1: Asian, non-Hispanic ONLY",
      RACETHM =="2"	~ "2: American Indian/Alaska Native, non-Hispanic ONLY",
      RACETHM =="3"	~ "3: Black, non-Hispanic ONLY",
      RACETHM =="4"	~ "4: Hispanic, any race",
      RACETHM =="5"	~ "5: White, non-Hispanic ONLY",
      RACETHM =="6"	~ "6: Non-Hispanic Native Hawaiian/Other Pacific Islander ONLY",
      RACETHM =="7"	~ "7: Multiple Race, non-Hispanic",
      TRUE ~ "NA"),
    COHORT = case_when(
      COHORT =="E"	~ "E: NSCG - 2011 ACS",
      COHORT =="F"	~ "F: NSCG - 2013 ACS",
      COHORT =="G"	~ "G: NSCG - 2015 ACS",
      COHORT =="H"	~ "H: NSCG - 2017 ACS",
      TRUE ~ "NA"),
    BAPBPR = case_when(
      BAPBPR =="1"~ "1: Publicly controlled",
      BAPBPR =="2"	~ "2: Privately controlled",
      BAPBPR =="L"	~ "L: Logical Skip",
      BAPBPR =="M"	~ "M: Public/Private status information is not available",
      TRUE ~ "NA"),
    DGRDG = case_when(
      DGRDG =="0"	~ "0: No specific degree",
      DGRDG =="1"	~ "1: Bachelor''s",
      DGRDG =="2"	~ "2: Master''s",
      DGRDG =="3"	~ "3: Doctorate",
      DGRDG =="4"	~ "4: Professional",
      DGRDG =="5"	~ "5: Other",
      DGRDG =="L"	~ "L: Logical Skip",
      TRUE ~ "NA"),
    NBAMEBG = case_when(
      NBAMEBG =="1"	~ "1: S&E fields",
      NBAMEBG =="2"	~ "2: S&E related fields",
      NBAMEBG =="3"	~ "3: Non-S&E fields",
      NBAMEBG =="4"	~ "4: Logical skip",
      TRUE ~ "NA"),
    NBAMEMG = case_when(
      NBAMEMG =="1"	~ "1: Computer and mathematical sciences",
      NBAMEMG =="2"	~ "2: Biological, agricultural and environmental life sciences",
      NBAMEMG =="3"	~ "3: Physical and related sciences",
      NBAMEMG =="4"	~ "4: Social and related sciences",
      NBAMEMG =="5"	~ "5: Engineering",
      NBAMEMG =="6"	~ "6: S&E-Related Fields",
      NBAMEMG =="7"	~ "7: Non-S&E Fields",
      NBAMEMG =="8"	~ "8: Logical Skip",
      NBAMEMG =="9"	~ "9: Other categories",
      TRUE ~ "NA"),
    NBAMENG = case_when(
      NBAMENG == "11"	~ "11: Computer and information sciences",
      NBAMENG =="12"	~ "12: Mathematics and statistics",
      NBAMENG =="21"	~ "21: Agricultural and food sciences",
      NBAMENG =="22"	~ "22: Biological sciences",
      NBAMENG =="23"	~ "23: Environmental life sciences",
      NBAMENG =="31"	~ "31: Chemistry, except biochemistry",
      NBAMENG =="32"	~ "32: Earth, atmospheric and ocean sciences",
      NBAMENG =="33"	~ "33: Physics and astronomy",
      NBAMENG == "34"	~ "34: Other physical sciences",
      NBAMENG =="41"	~ "41: Economics",
      NBAMENG =="42"	~ "42: Political and related sciences",
      NBAMENG =="43"	~ "43: Psychology",
      NBAMENG =="44"	~ "44: Sociology and anthropology",
      NBAMENG =="45"	~ "45: Other social sciences",
      NBAMENG =="51"	~ "51: Aerospace, aeronautical and astronautical engineering",
      NBAMENG =="52"	~ "52: Chemical engineering",
      NBAMENG =="53"	~ "53: Civil and architectural engineering",
      NBAMENG =="54"	~ "54: Electrical and computer engineering",
      NBAMENG =="55"	~ "55: Industrial engineering",
      NBAMENG =="56"	~ "56: Mechanical engineering",
      NBAMENG =="57"	~ "57: Other engineering",
      NBAMENG =="61"	~ "61: Health",
      NBAMENG =="62"	~ "62: Science and mathematics teacher education",
      NBAMENG =="63"	~ "63: Technology and Technical Fields",
      NBAMENG =="64"	~ "64: Other S&E related fields",
      NBAMENG =="71"	~ "71: Management and administration fields",
      NBAMENG =="72"	~ "72: Education, except science and math teacher education",
      NBAMENG =="73"	~ "73: Social service and related fields",
      NBAMENG =="74"	~ "74: Sales and marketing fields",
      NBAMENG =="75"	~ "75: Art and Humanities Fields",
      NBAMENG =="76"	~ "76: Other Non-S&E fields",
      NBAMENG =="98"	~ "98: Logical Skip",
      NBAMENG =="99"	~ "99: Other categories",
      TRUE ~ "NA"),
    EDDAD = case_when(
      EDDAD =="1"	~ "1: Less than high school completed",
      EDDAD =="2"	~ "2: High school diploma or equivalent",
      EDDAD =="3"	~ "3: Some college, vocational, or trade school (including 2-year degrees)",
      EDDAD =="4"	~ "4: Bachelors degree (e.g. BS, BA, AB)",
      EDDAD =="5"	~ "5: Masters degree (e.g. MS, MA, MBA)",
      EDDAD =="6"	~ "6: Professional degree (e.g. JD, LLB, MD, DDS, etc.)",
      EDDAD =="7"	~ "7: Doctorate (e.g. PhD, DSc, EdD, etc.)",
      EDDAD =="8"	~ "8: Not applicable",
      TRUE ~ "NA"),
    EDMOM = case_when(
      EDMOM =="1"	~ "1: Less than high school completed",
      EDMOM =="2"	~ "2: High school diploma or equivalent",
      EDMOM =="3"	~ "3: Some college, vocational, or trade school (including 2-year degrees)",
      EDMOM =="4"	~ "4: Bachelors degree (e.g. BS, BA, AB)",
      EDMOM =="5"	~ "5: Masters degree (e.g. MS, MA, MBA)",
      EDMOM =="6"	~ "6: Professional degree (e.g. JD, LLB, MD, DDS, etc.)",
      EDMOM =="7"	~ "7: Doctorate (e.g. PhD, DSc, EdD, etc.)",
      EDMOM =="8"	~ "8: Not applicable",
      TRUE ~ "NA"),
    EMSECSM = case_when(
      EMSECSM == "1"	~ "1: Educational Institution",
      EMSECSM == "2"	~ "2: Government",
      EMSECSM == "3"	~ "3: Business/Industry",
      EMSECSM == "L"	~ "L: Logical Skip",
      TRUE ~ "NA"),
    EMTP = case_when(
      EMTP == "01"~ "01: Elementary, middle, or secondary school",
      EMTP =="02"	~ "02: 2-year college, junior college, or technical institute",
      EMTP =="03"	~ "03: 4-year college or university",
      EMTP =="04"	~ "04: Medical school",
      EMTP =="05"	~ "05: University research institute",
      EMTP =="06"	~ "06: Other (Educational Institution)",
      EMTP =="10"	~ "10: Private for-profit (non-educational institution)",
      EMTP =="11"	~ "11: Private non-profit (non-educational institution)",
      EMTP =="12"	~ "12: Self-employed, not incorporated (non-educational institution)",
      EMTP =="13"	~ "13: Self-employed, incorporated (non-educational institution)",
      EMTP =="14"	~ "14: Local government (non-educational institution)",
      EMTP =="15"	~ "15: State government (non-educational institution)",
      EMTP =="16"	~ "16: U.S. military (non-educational institution)",
      EMTP =="17"	~ "17: U.S. government (non-educational institution)",
      EMTP =="18"	~ "18: Other (non-educational institution)",
      EMTP =="L"	~ "L: Logical Skip",
      TRUE ~ "NA")
    )
```

```{r}
write.csv(data_recode, "first selection recode.csv")
```


```{r}
data <- read.csv('first selection recode.csv')
```

```{r}
#create binary variables
data <- data %>%
  mutate(LFSTAT=as.numeric(LFSTAT),
         BAPBPR=as.factor(BAPBPR),
         BSDGN=as.numeric(BSDGN),
         BTHST=as.numeric(BTHST),
         CTZN=as.numeric(CTZN),
         HDACY3=as.numeric(HDACY3),
         WKSWK=as.numeric(WKSWK),
         WKSYR=as.factor(WKSYR),
         RESPLO3=as.factor(RESPLO3))%>%
  mutate(degree1 = case_when(NBAMEBG == '1: S&E fields' ~ 1,
                             NBAMEBG == '2:S&E related fields' ~ 1,
                             TRUE ~ 0),
         HSDAD = case_when(EDDAD == '1: Less than high school completed'~1,
                           EDDAD == '2: High school diploma or equivalent'~1,
                           EDDAD == '8: Not applicable'~1,
                           TRUE ~0),
         HSMOM = case_when(EDMOM == '1: Less than high school completed'~1,
                           EDMOM == '2: High school diploma or equivalent'~1,
                           EDMOM == '8: Not applicable'~1,
                           TRUE ~0),
        private = case_when(BAPBPR == '2: Privately controlled' ~ 1,
                            TRUE ~0),
        USDegree = case_when(BADGRUS == 'Y' ~ 1,
                             TRUE ~0),
        Female = case_when(GENDER == 'F' ~ 1,
                           TRUE ~0),
        Experience = 2019-HDACY3,
        Citizen = case_when(CTZN == '1' ~ 1,
                            CTZN == '2' ~ 1,
                            TRUE ~0))
```

```{r}

filtered <- data %>%
  filter(LFSTAT==1         #in labor force
         & BSDGN==1        #number of BA is 1
         #& CTZN!=4         #not temporary visa
         #& BADGRUS=="Y"    #BA degree in US
         & WKSYR==1        #worked full year
         & HRSWK >= 30     #Work full time
         & DGRDG=="1: Bachelor''s" #bachelor degree
         & EMUS=="Y"              #employer in US
         & SALARY > 0
         & EARN > 0
         & EARN != 9999998
         & EMTP != '12: Self-employed, not incorporated (non-educational institution)'
         & EMTP != '13: Self-employed, incorporated (non-educational institution)'
         & EMTP != '16: U.S. military (non-educational institution)'
         & NBAMENG != '8: Logical Skip') #not missing FoS

```

```{r}
#create binary variables for major NBAMENG
filtered <- filtered %>%
  mutate(CompSci = case_when(NBAMEMG == '1: Computer and mathematical sciences' ~ 1,
                             NBAMENG == '63: Technology and Technical Fields' ~ 1,
                             TRUE ~ 0),
         Biology = case_when(NBAMEMG == '2: Biological, agricultural and environmental life sciences' ~ 1,
                             TRUE ~ 0),
         Physical = case_when(NBAMEMG == '3: Physical and related sciences' ~ 1,
                             TRUE ~ 0),
         SocialSci = case_when(NBAMEMG == '4: Social and related sciences' ~ 1,
                             TRUE ~ 0),
         Engineering = case_when(NBAMEMG == '5: Engineering' ~ 1,
                             TRUE ~ 0),
         Health = case_when(NBAMEMG == '6: S&E-Related Fields' & NBAMENG == '61: Health' ~ 1 ,
                            NBAMEMG == '6: S&E-Related Fields' & NBAMENG == '64: Other S&E related fields' ~ 1,
                             TRUE ~ 0),
         Management = case_when(NBAMEMG == '7: Non-S&E Fields' & 
                             NBAMENG == '71: Management and administration fields'~ 1,
                             TRUE ~ 0),
         Education = case_when(NBAMEMG == '6: S&E-Related Fields' & 
                                 NBAMENG == '62: Science and mathematics teacher education'~ 1,
                             NBAMENG == '72: Education, except science and math teacher education'~ 1,
                             TRUE ~ 0),
         Arts = case_when(NBAMEMG == '7: Non-S&E Fields' & 
                             NBAMENG == '75: Art and Humanities Fields'~ 1,
                             TRUE ~ 0),
         Other = case_when(NBAMEMG == '7: Non-S&E Fields' & 
                             NBAMENG == '73: Social service and related fields'~ 1,
                             NBAMEMG == '7: Non-S&E Fields' &
                             NBAMENG == '74: Sales and marketing fields'~ 1,
                             NBAMEMG == '7: Non-S&E Fields' &
                             NBAMENG == '76: Other Non-S&E fields'~ 1,
                             TRUE ~ 0)
        )

filtered <- filtered %>%
  mutate( AllMajor = case_when(CompSci == 1 ~ 'Computer Science',
                               Biology == 1 ~ 'Biology',
                               Physical == 1 ~ 'Physical',
                               SocialSci == 1 ~ 'Social Science',
                               Engineering == 1 ~ 'Engineering',
                               Health == 1 ~ 'Health',
                               Management == 1 ~ 'Management',
                               Education == 1 ~ 'Education',
                               Arts == 1 ~ 'Arts',
                               Other == 1 ~ 'Other',
                               TRUE ~ NA))

```


```{r}
filtered <- filtered %>%
  rename(Salary = SALARY,
         Age = AGE,
         Minority = MINRTY,
         Disable = HCAPIN,
         US_Degree = BADGRUS,
         Private = private)
```


```{r}
#plot salary scatter plot, see outliers
ggplot(filtered, aes(x=HDACY3, y=log(Salary)))+
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Salary by Graduation Year",
       x = "Graduation Year",
       y = "Salary")
```

```{r}
#remove too low values
filtered <- filtered %>%
  filter(Salary >= exp(9))

```


```{r}
write.csv(filtered, "filtered.csv")
```


